### ISSUE TITLE
The blocks javascript files are duplicated in the Java source code folder

### ISSUE THREAD

**Issue by ItsHarper** [OpenFTC/Extracted-RC_Updater#1]
See [here](https://github.com/OpenFTC/Extracted-RC/tree/a8b07bb025455be86294d252c4ca752af7a4b505/Blocks/src/main/java/blocks) and [here](https://github.com/OpenFTC/Extracted-RC/tree/a8b07bb025455be86294d252c4ca752af7a4b505/Blocks/src/main/assets/blocks).

They only need to be in the assets folder.

**Comment by Windwoes** [comment]
Actually, it appears that they are duplicated in the official AAR/sourceJar.... maybe we need to tweak the internal release script?

**Comment by ItsHarper** [comment]
Ohh, they normally get packaged in the aar, but they're probably in the source jar for ease of accessing them. I'd change the behavior of this repository to ignore the src/blocks folder.

**Comment by Windwoes** [comment]
> 
> 
> Ohh, they normally get packaged in the aar, but they're probably in the source jar for ease of accessing them. I'd change the behavior of this repository to ignore the src/blocks folder.

You mean `src/main/java/blocks`?

**Comment by ItsHarper** [comment]
> > 
> > 
> > Ohh, they normally get packaged in the aar, but they're probably in the source jar for ease of accessing them. I'd change the behavior of this repository to ignore the src/blocks folder.
> 
> You mean `src/main/java/blocks`?

Yep.

**Comment by Windwoes** [comment]
Not an issue anymore because 5.5 release doesn't duplicate them in the source JAR
